export const browserCoreExamples = [
  "dryads-ai browser status",
  "dryads-ai browser start",
  "dryads-ai browser stop",
  "dryads-ai browser tabs",
  "dryads-ai browser open https://example.com",
  "dryads-ai browser focus abcd1234",
  "dryads-ai browser close abcd1234",
  "dryads-ai browser screenshot",
  "dryads-ai browser screenshot --full-page",
  "dryads-ai browser screenshot --ref 12",
  "dryads-ai browser snapshot",
  "dryads-ai browser snapshot --format aria --limit 200",
  "dryads-ai browser snapshot --efficient",
  "dryads-ai browser snapshot --labels",
];

export const browserActionExamples = [
  "dryads-ai browser navigate https://example.com",
  "dryads-ai browser resize 1280 720",
  "dryads-ai browser click 12 --double",
  'dryads-ai browser type 23 "hello" --submit',
  "dryads-ai browser press Enter",
  "dryads-ai browser hover 44",
  "dryads-ai browser drag 10 11",
  "dryads-ai browser select 9 OptionA OptionB",
  "dryads-ai browser upload /tmp/dryads-ai/uploads/file.pdf",
  'dryads-ai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dryads-ai browser dialog --accept",
  'dryads-ai browser wait --text "Done"',
  "dryads-ai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dryads-ai browser console --level error",
  "dryads-ai browser pdf",
];
