export const browserCoreExamples = [
  "dmms-ai browser status",
  "dmms-ai browser start",
  "dmms-ai browser stop",
  "dmms-ai browser tabs",
  "dmms-ai browser open https://example.com",
  "dmms-ai browser focus abcd1234",
  "dmms-ai browser close abcd1234",
  "dmms-ai browser screenshot",
  "dmms-ai browser screenshot --full-page",
  "dmms-ai browser screenshot --ref 12",
  "dmms-ai browser snapshot",
  "dmms-ai browser snapshot --format aria --limit 200",
  "dmms-ai browser snapshot --efficient",
  "dmms-ai browser snapshot --labels",
];

export const browserActionExamples = [
  "dmms-ai browser navigate https://example.com",
  "dmms-ai browser resize 1280 720",
  "dmms-ai browser click 12 --double",
  'dmms-ai browser type 23 "hello" --submit',
  "dmms-ai browser press Enter",
  "dmms-ai browser hover 44",
  "dmms-ai browser drag 10 11",
  "dmms-ai browser select 9 OptionA OptionB",
  "dmms-ai browser upload /tmp/dmms-ai/uploads/file.pdf",
  'dmms-ai browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dmms-ai browser dialog --accept",
  'dmms-ai browser wait --text "Done"',
  "dmms-ai browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dmms-ai browser console --level error",
  "dmms-ai browser pdf",
];
